# docker-compose.yml
version: '3'

services:

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-config:/etc/mongo-config
      - ./mongo-data:/data/db:rw
      - ./mongo-logs:/var/log/mongodb:rw
    command: mongod --config /etc/mongo-config/mongod.conf
    networks:
      - default
    
  flaskapprr:
    build: .
    volumes:
      - ./app:/app/
    environment:
      - PYTHONUNBUFFERED=1
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_web
      traefik.http.routers.flaskapprr.entrypoints: websecure
      traefik.http.routers.flaskapprr.rule: 'Host(`rr.alkemata.com`)'
      traefik.http.services.flaskapprr.loadbalancer.server.port: 5000
    networks:
      - traefik_web
      - default
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/flaskdb


networks:
  traefik_web:
    external: true

volumes:
  mongo-data:
