# docker-compose.yml
version: '3'

services:

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: mongod
    networks:
      - default
    
  flaskapp:
    build: .
    volumes:
      - ./app:/app/
    environment:
      - PYTHONUNBUFFERED=1
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_web
      traefik.http.routers.flaskapp.entrypoints: websecure
      traefik.http.routers.flaskapp.rule: 'Host(`rr.alkemata.com`)'
      traefik.http.services.flaskapp.loadbalancer.server.port: 5000
    networks:
      - traefik_web
      - jup_default
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/flaskdb


networks:
  traefik_web:
    external: true
  jup_default:
    external: true

volumes:
  mongo-data:
